# Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# Browser
browser = chrome

# Credentials
userName = Admin
password = admin123

#Implicit wait (sec)
implicitWait=10